import React from 'react'
import { useState,useEffect } from 'react'
import {Loader,Card,FormField} from "../components";

const Rendercards=({data,title})=>{
  if(data?.length>0)
    return data.map((post)=><Card key={post._id} {...post}></Card>)
  return (
    <h2 className='mt-5 font-bold text-[#6449ff] text-x1 uppercase'>{title}</h2>
  )

}

const Home = () => {
  const [loading,setloading] = useState(false);
  const [allposts,setallposts]=useState(null);
  const [searchText,setsearchText]=useState('');
  const [ SearchResults,setSearchResults]=useState(null);
  const [SearchTimeout,SetSearchTimeout] = useState(null);
  useEffect(()=>{
    const fetchPosts= async ()=>{
      setloading(true);
      try {
        const response = await fetch('https://image-generation-kwo4.onrender.com/api/v1/post',{
          method:'GET',
          headers:{
            'Content-Type':'application/json',
          },
        })
        if(response.ok){
          const result=await response.json();
          setallposts(result.data.reverse());
        }
      } catch (error) {
        alert(error);
      }finally{
        setloading(false);
      }
    }
    fetchPosts();
  },[]);

  const handleSearchChange = (e)=>{
    setsearchText(e.target.value);
    SetSearchTimeout(()=>{
      setTimeout(()=>{
      const SearchResults = allposts.filter((items)=>items.name.toLowerCase().includes(searchText.toLowerCase())|| items.prompt.toLowerCase().includes(searchText.toLowerCase()));
      setSearchResults(SearchResults);
    },500)
    })

  }

  return (
    <section className='max-w-7x1 mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          Dream it. DALL·E will create it.
        </h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
          Browse through a collection of imaginative and visually stunning images generated by DREAM-DALLE
        </p>
      </div>
      <div className='mt-16'>
        <FormField
        LabelName="Search Post"
        name="text"
        type="text"
        placeholder="Search Posts"
        value={searchText}
        handleChange={handleSearchChange}
        ></FormField>
      </div>
      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader/>
          </div>

        ):(
          <>
          {searchText && (
            <h2 className='font-medium text-[#666e75] text-x1 mb-3'>Showing results for '<span className='text-[#222328]'>
              {searchText}
              </span>
              </h2>
          )}
          <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-col-1 gap-3'>
            {searchText ?( 
              <Rendercards
              data={SearchResults}
              title="No Results Found"></Rendercards>
            ):(
              <Rendercards
              data={allposts}
              title="No Posts Found"></Rendercards>
            ) }
          </div>


          </>
        )}
      </div>



    </section>
  )
}

export default Home